"""Создание таблицы User

Revision ID: 08e6fbb9a513
Revises: 
Create Date: 2023-07-31 14:04:33.030441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08e6fbb9a513"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fullname", sa.VARCHAR(length=129), nullable=True),
        sa.Column("username", sa.VARCHAR(length=32), nullable=True),
        sa.Column("locale", sa.VARCHAR(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
